server:
  port: 8084

spring:
  application:
    name: customer
  cloud:
    nacos:
      config:
        enabled: false
        server-addr: 192.168.190.130:8848
        file-extension: yaml
        namespace: 306dc2d0-9a77-44d3-8ff6-8653450d4d14
        group: test_GROUP
      discovery:
        server-addr: 192.168.190.130:8848

      #dataid 自动拼装